SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM
    (
    SELECT *
    FROM ANIMAL_INS I
    WHERE SEX_UPON_INTAKE LIKE "%Intact%"
    ) SQ1, ANIMAL_OUTS O
WHERE SQ1.ANIMAL_ID = O.ANIMAL_ID
AND O.SEX_UPON_OUTCOME NOT LIKE "%Intact%"